### ISSUE TITLE
React Quick Start page is outdated with release of new @micro-stacks/react

### ISSUE THREAD

**Issue by LCBradley3k** [fungible-systems/micro-stacks#33]
https://github.com/fungible-systems/micro-stacks/blob/main/docs/react-quick-start.md

Great to see a helpful library like this, but with the major updates the outdated documentation can make it pretty confusing. One idea is to remove this page, and create a new quickstart guide at [micro-stacks-react](https://github.com/fungible-systems/micro-stacks-react)

**Comment by dcsan** [comment]
Yeah i'm hitting similar issues. The quick-start here
https://github.com/fungible-systems/micro-stacks/blob/main/docs/react-quick-start.md

seems to refer to 

`import { MicroStacksProvider } from "./react";`

i was also looking into this project which seems to use these libs
https://github.com/EscapeLabs/nft-nyc-exclusive-app

`import { MicroStacksProvider, useUserData, useAuth } from 'micro-stacks/react';`

separately there is `micro-stacks` and `micro-stacks/react` which are pegged at different versions...

a bit confused what to use! did you figure it out?

**Comment by aviculturist** [comment]
Some of the opinionated `micro-stacks` integrations for `react` and `nextjs` were moved to separate packages. The official example repo is here, which may help. I've had good success running the `nextjs` example in particular.

**Comment by dcsan** [comment]
thanks! i'm not clear which is more recent or deprecated 

https://github.com/fungible-systems/micro-stacks
https://github.com/fungible-systems/micro-stacks-react

or if they resolve to the same packages?
given some example code like `import { MicroStacksProvider } from "./react";` which is even *more* confusing - perhaps that's a relative link during package development?

this stuff appears to be changing rapidly and I worry about smashing my head against the wall on something that is obsolete/known to be broken due to package upgrades. Be happy to contribute even but wanted to know the ground truth to start with!

@aulneau

**Comment by aulneau** [comment]
Hi everyone! so sorry i missed these comments!

Very exciting that you are starting to play around.

It's true, the react packages have been moved to `@micro-stacks/react`, `@micro-stacks/query` and `@micro-stacks/nextjs`. I have not yet updated the quick start guide to point to those libraries, but I will make sure to do that this week.

> this stuff appears to be changing rapidly and I worry about smashing my head against the wall on something that is obsolete/known to be broken due to package upgrades. Be happy to contribute even but wanted to know the ground truth to start with!

Yep it is changing a bit, but I would say it's slowing down. I'm going to be setting up a basic docs site soon which should outline the initial patterns for adding auth, storage, etc. I will comment on this issue when that is done!

**Comment by dcsan** [comment]
awesome thanks for the update. 

So I should just use:
https://github.com/fungible-systems/micro-stacks-react

and consider deprecated:
https://github.com/fungible-systems/micro-stacks

**Comment by aulneau** [comment]
> awesome thanks for the update.
> 
> So I should just use: https://github.com/fungible-systems/micro-stacks-react
> 
> and consider deprecated: https://github.com/fungible-systems/micro-stacks

Both are still used, but the core Library `micro-stacks` no longer has the react sub module, it's the core functionality that powers the new, separate react library. Any other framework integration will make use of it too.

**Comment by aulneau** [comment]
Hi everyone!

Here is an early draft of the documentation for micro-stacks and the react integration, https://docs.micro-stacks.dev/modules/integrations/react

still a lot of missing content, but some stuff here should be helpful!

**Comment by dcsan** [comment]
🔥 🔥  this is great!

btw as a newcomer to stx ecosystem the differences part is exactly what i was looking for:
https://docs.micro-stacks.dev/#differences-from-stacks.js

so basically 
- a much smaller bundle size 'cos none of those crypto libs are in your module
- using jotai and query instead of `connect`
- some differences in how auth works... ?

can the two codebases work together? eg if i'm signing in using the stacks lib, it's propagating my session info etc in a connect wrapper, that seems pretty incompatible with jotai (which looks nice btw)

**Comment by aulneau** [comment]
> using jotai and query instead of connect

Yeah, as a consumer of `@micro-stacks/react`, you really don't have to know that it's using jotai behind the scenes.

> some differences in how auth works... ?

The underlying mechanism is the same. not sure what you mean

> can the two codebases work together? eg if i'm signing in using the stacks lib, it's propagating my session info etc in a connect wrapper, that seems pretty incompatible with jotai (which looks nice btw)

Certain elements can work. Eg you can use clarity values from both, or `StacksTransaction`, but auth and session storage are different.

stacks.js (made up of many `@stacks/*` packages) and `@stacks/connect`/`@stacks/connect-react` are the two sets of libraries that have traditionally been used to make apps. the stacks.js libs are generic and not tied to any frontend framework, connect is used to connect to the web wallet/authenticator, and the react package is some abstractions on all of the previously mentioned libs to use in react.

With micro-stacks, the primary package `micro-stacks` is completely unrelated to any framework. It can be used in node, deno, cloudflare workers, etc. it's one library with many sub-modules, eg `micro-stacks/clarity`.

`@micro-stacks/react`, `@micro-stacks/nextjs`, `@micro-stacks/query` are all _very_ opinionated libraries for building advanced and complex react-based stacks apps. Yes, they use jotai and react-query behind the scenes, but as an app dev you don't have to ever directly interact with jotai or react-query.

Hope this helps!

**Comment by aulneau** [comment]
https://docs.micro-stacks.dev/modules/integrations/react has been updated -- going to close this issue for now, but reopen if you are still having troubles
