### ISSUE TITLE
how to make an authenticate button?

### ISSUE THREAD

**Issue by dcsan** [fungible-systems/micro-stacks#38]
I'm trying to build a simple auth button, similar to this
https://github.com/hirosystems/nft-nyc-exclusive-app/blob/master/components/auth.js

however getting this error below.

I log the values passed to the hook before calling it and they are there...

![image](https://user-images.githubusercontent.com/514002/141751078-19b3e112-cd97-4c49-97e3-4157177cfe36.png)

on further details it seems I can't pass params into the function, I have to stash them in a jotai atom. 
I couldn't quite figure out how to do this, is there an example?
Or is there another component I can use to just pass the params directly?

I saw other docs to wrap everything in `MicroStacksProvider`, but that doesn't exist now?

// import  { MicroStacksProvider } from '@micro-stacks/react';  // does not exist

```ts

import { Text, Center, VStack, Button, Link } from '@chakra-ui/react';
import { useAuth } from '@micro-stacks/react';

// import  { MicroStacksProvider } from '@micro-stacks/react';  // does not exist
interface AuthOptions {
  // onFinish?: (payload: StacksSessionState) => void;
  onFinish?: any
  onCancel?: (error?: Error) => void;
  onSignOut?: () => void;
  // scopes?: AuthScope[];
  appDetails: AppDetails;
}

interface AppDetails {
  name: string;
  icon: string;
}

export const AuthenticateButton = () => {
  const { handleSignIn, isLoading } = useAuth();

  const appDetails: AppDetails = {
    name: 'Minter',
    icon: '/assets/astro/zodiac-200.png',
  }

  const authOptions: AuthOptions = {
    appDetails,
    onFinish: (payload: any) => {
      console.log('onFinish', payload);
    }
  }

  const doSignIn = () => {
    console.log('doSignIn.authOptions', authOptions);
    // @ts-ignore
    handleSignIn(authOptions)
  }

  return (
    <Center>
      <VStack>

        <Button
          size='lg'
          p={10}
          onClick={doSignIn}
        >
          <Text>Sign in</Text>
        </Button>
      </VStack>
    </Center>
  )
}


export default AuthenticateButton;

```

**Comment by aviculturist** [comment]
Check this example: https://github.com/fungible-systems/micro-stacks-examples/blob/main/nextjs/components/wallet-connect-button.tsx

**Comment by aulneau** [comment]
https://docs.micro-stacks.dev/modules/integrations/react/authentication has been updated! going to close this for now, but feel free to reopen if there are issues still

**Comment by MyNameIsNeXTSTEP** [comment]
> https://docs.micro-stacks.dev/modules/integrations/react/authentication has been updated! going to close this for now, but feel free to reopen if there are issues still

Page now is not available*
404 error
