### ISSUE TITLE
de-serialization?

### ISSUE THREAD

**Issue by dcsan** [fungible-systems/micro-stacks#59]
you have some docs on 
https://docs.micro-stacks.dev/modules/core/clarity/serialization

do you have examples of how to decode the data coming back from the APIs?
eg i sent a buffer in and returns 

```
{
  type: '(optional (buff 64))',
  value: {
    type: '(buff 64)',
    value: '0x36333562663261376537333436376636333363313931353738613938383137313663383633306235373164613034643634303334356331646232333231636537'
  }
}
```

any docs on how to convert that to a useful value?

**Comment by dcsan** [comment]
eg the opposite of `bufferCVFromString(seed)`

**Comment by aulneau** [comment]
There are a few options:
```
import {hexToValue} from 'micro-stacks/clarity';
import {hexToCv} from 'micro-stacks/clarity';
import {cvToTrueValue} from 'micro-stacks/clarity';
```
I'd recommend always using `cvToTrueValue` or `hexToValue`
